<?php
declare(strict_types=1);
/**
 * @by SwiftOtter, Inc. 6/5/20
 * @website https://swiftotter.com
 **/

namespace SwiftOtter\GiftCard\Ui\Component;

use Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider as AbstractDataProvider;

class DataProvider extends AbstractDataProvider
{
    public function getData()
    {
        return parent::getData(); // TODO: Change the autogenerated stub
    }


}