<?php
declare(strict_types=1);
/**
 * @by SwiftOtter, Inc. 8/18/20
 * @website https://swiftotter.com
 **/
/** @var $block \Magento\Framework\View\Element\Template */
?>
<script type="text/javascript">
    require([], function () {
        let updated = {
            ...JSON.parse(window.localStorage.getItem('so-auth') || '{}'),
            has_account: true,
            logged_in: true
        };

        window.localStorage.setItem('so-auth', JSON.stringify(updated));
    });
</script>
